swagger: "2.0"
info:
  title: ODM2 REST API
  version: v1
  contact: 
    email: landungs@uw.edu
    name: Landung Setiawan
  description: This is a development version for ODM2 REST API
host: 127.0.0.1:8000
basePath: /v1
tags:
  - name: affiliations
    description: Affiliations in database
  - name: actions
    description: Actions in database
  - name: people
    description: People in database
  - name: results
    description: Results in database
  - name: resultvalues
    description: Get values of Results in database
  - name: samplingfeatures
    description: Sampling Features in database
  - name: datasets
    description: Data Sets in database
  - name: methods
    description: Methods in database
  - name: samplingfeaturedatasets
    description: DataSets in database for a given set of SamplingFeatures
  - name: variables
    description: Variables in database
  - name: units
    description: Units in database
  - name: organizations
    description: Organizations in database
  - name: datasetresults
    description: DatasetResults in database
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  - application/yaml
  - text/csv
paths:
  /affiliations:
    get:
      tags:
      - affiliations
      operationId: getAffiliations
      summary: ODM2 affiliations retrieval by Affiliation ID(s)
      parameters:
        - name: affiliationID
          in: query
          description: Affiliation ID(s)
          required: false
          type: string 
        - name: firstName
          in: query
          description: Person First Name
          required: false
          type: string
        - name: lastName
          in: query
          description: Person Last Name
          required: false
          type: string
        - name: organizationCode
          in: query
          description: Organization Code
          required: false
          type: string 
      responses:
        "200":
          description: 200 Response
  /people:
    get:
      tags:
      - people
      operationId: getPeopleVersion1
      summary: All ODM2 people retrieval.
      parameters:
        - name: peopleID
          in: query
          description: People ID(s)
          required: false
          type: string
        - name: firstName
          in: query
          description: Person First Name
          required: false
          type: string
        - name: lastName
          in: query
          description: Person Last Name
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /results:
    get:
      tags:
      - results
      operationId: getResultsVersion1
      summary: All ODM2 results retrieval.
      parameters:
        - name: resultID
          in: query
          description: Result ID(s)
          required: false
          type: string
        - name: resultUUID
          in: query
          description: Result UUID(s)
          required: false
          type: string
        - name: resultType
          in: query
          description: Result Type (Name). <br>
                       See all available Result Types [here](http://vocabulary.odm2.org/resulttype/).
          required: false
          type: integer
        - name: actionID
          in: query
          description: Action ID
          required: false
          type: integer
        - name: samplingFeatureID
          in: query
          description: Sampling Feature ID
          required: false
          type: integer
        - name: siteID
          in: query
          description: Site ID
          required: false
          type: integer
        - name: variableID
          in: query
          description: Variable ID
          required: false
          type: integer
        - name: simulationID
          in: query
          description: Simulation ID
          required: false
          type: integer
      responses:
        "200":
          description: 200 Response
  /resultvalues:
      get:
        tags:
        - resultvalues
        operationId: getResultValuesByResultID
        summary: ODM2 result values retrieval by Result ID(s)
        parameters:
          - name: resultID
            in: query
            description: Result ID(s)
            required: true
            type: string
          - name: beginDate
            in: query
            description: Begin Date 'yyyy-mm-dd hh:mm:ss'
            required: false
            type: string
          - name: endDate
            in: query
            description: End Date 'yyyy-mm-dd hh:mm:ss'
            required: false
            type: string
        responses:
          "200":
            description: 200 Response
  /samplingfeaturedatasets:
    get:
      tags:
      - samplingfeaturedatasets
      operationId: getSamplingFeatureDatasets
      summary: Get ODM2 Datasets for given set of SamplingFeatures
      parameters:
        - name: samplingFeatureID
          description: SamplingFeature ID(s) **Required (or SamplingfeatureUUID)**
          required: false
          in: query
          type: string
        - name: samplingFeatureUUID
          description: SamplingFeature UUID(s) **Required (or SamplingFeatureID)**
          required: false
          in: query
          type: string
        - name: SamplingFeatureCode
          description: SamplingFeature Code(s)
          required: false
          in: query
          type: string
        - name: datasetType
          description: Dataset Type (Name). <br>
                       See all available Dataset Types [here](http://vocabulary.odm2.org/datasettype/).
          required: false
          in: query
          type: string
      responses:
        "200":
          description: 200 Response
  /samplingfeatures:
    get:
      tags:
      - samplingfeatures
      operationId: getSamplingFeatures
      summary: All ODM2 samplingfeatures retrieval.
      parameters:
        - name: samplingFeatureID
          in: query
          description: Sampling Feature ID(s)
          required: false
          type: string
        - name: samplingFeatureCode
          in: query
          description: Sampling Feature Code(s)
          required: false
          type: string
        - name: samplingFeatureType
          in: query
          description: Sampling Feature Type (Name). <br>
                       See all available Sampling Feature Types [here](http://vocabulary.odm2.org/samplingfeaturetype/).
          required: false
          type: string 
        - name: results
          in: query
          description: Get Sampling Features that has Results
          required: false
          type: boolean
      produces:
      - application/json
      - application/yaml
      responses:
        "200":
          description: 200 Response
  /datasets:
    get:
      tags:
      - datasets
      operationId: getDataSets
      summary: All ODM2 datasets retrieval.
      parameters:
        - name: datasetUUID
          in: query
          description: Data Set UUID(s)
          required: false
          type: string
        - name: datasetCode
          in: query
          description: Data Set Code(s)
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /methods:
    get:
      tags:
      - methods
      operationId: getMethods
      summary: All ODM2 methods retrieval
      parameters:
        - name: methodCode
          in: query
          description: Method Code(s)
          required: false
          type: string
        - name: methodID
          in: query
          description: Method ID(s)
          required: false
          type: string
        - name: methodType
          in: query
          description: Method Type (Name). <br>
                       See all available Method Types [here](http://vocabulary.odm2.org/methodtype/).
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /actions:
    get:
      tags:
        - actions
      operationId: getActions
      summary: All ODM2 actions retrieval
      parameters:
        - name: actionID
          in: query
          description: Action ID(s)
          required: false
          type: string
        - name: actionType
          in: query
          description: Action Type (Name). <br> 
                       See all available Action Types [here](http://vocabulary.odm2.org/actiontype/).
          required: false
          type: string
        - name: samplingFeatureID
          in: query
          description: Sampling Feature ID
          required: false
          type: integer
      responses:
        "200":
          description: 200 Response
  /variables:
    get:
      tags:
        - variables
      operationId: getVariables
      summary: All ODM2 variables retrieval
      parameters:
        - name: variableID
          in: query
          description: Variable ID(s)
          required: false
          type: string
        - name: variableCode
          in: query
          description: Variable Code(s)
          required: false
          type: string
        - name: siteCode
          in: query
          description: Sampling Feature ID
          required: false
          type: integer
        - name: results
          in: query
          required: false
          type: boolean
      responses:
        "200":
          description: 200 Response
  /units:
    get:
      tags:
        - units
      operationId: getUnits
      summary: All ODM2 units retrieval
      parameters:
        - name: unitsID
          in: query
          description: Units ID(s)
          required: false
          type: string
        - name: unitsName
          in: query
          description: Units Name
          required: false
          type: string
        - name: unitsType
          in: query
          description: Units Type (Name). <br> 
                       See all available Units Types [here](http://vocabulary.odm2.org/unitstype/).
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /organizations:
    get:
      tags:
        - organizations
      operationId: getOrganizations
      summary: All ODM2 organizations retrieval
      parameters:
        - name: organizationID
          in: query
          description: Organization ID(s)
          required: false
          type: string
        - name: organizationCode
          in: query
          description: Organization Code(s)
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
  /datasetresults:
    get:
      tags:
        - datasetresults
      operationId: getDatasetResults
      summary: All ODM2 Dataset Results retrieval
      parameters:
        - name: datasetID
          in: query
          description: Dataset ID(s) **Required (or Dataset UUID or Dataset Code)**
          required: false
          type: string
        - name: datasetUUID
          in: query
          description: Dataset UUID(s) **Required (or Dataset ID or Dataset Code)**
          required: false
          type: string
        - name: datasetCode
          in: query
          description: Dataset Code(s) **Required (or Dataset ID or Dataset UUID)**
          required: false
          type: string
        - name: datasetType
          in: query
          description: Dataset Type (Name). <br> 
                       See all available Dataset Types [here](http://vocabulary.odm2.org/datasettype/).
          required: false
          type: string
      responses:
        "200":
          description: 200 Response
